# Generated by Django 3.0.1 on 2020-01-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='viewsCount',
            new_name='viewCount',
        ),
    ]
