# Generated by Django 3.0.1 on 2020-01-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200107_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='iconograph',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/'),
        ),
    ]
