# Generated by Django 3.0.1 on 2020-01-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_iconograph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='iconograph',
            new_name='titleIconograph',
        ),
    ]
