# Generated by Django 3.0.1 on 2020-01-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200115_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='titleIconograph',
            new_name='iconograph',
        ),
        migrations.RemoveField(
            model_name='article',
            name='bodyIconograph',
        ),
    ]
