# Generated by Django 3.0.1 on 2020-01-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20200115_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='isRecommend',
        ),
        migrations.AddField(
            model_name='article',
            name='topRecommend',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
        migrations.AlterField(
            model_name='article',
            name='iconograph',
            field=models.ImageField(blank=True, upload_to='articleIconograph/'),
        ),
    ]
